#!/bin/bash
##
## uses xinput to toggle touchpad state
## 10/3/2018
## Bryton J Smith
##

mapfile -t id < <( xinput --list | grep "Touchpad" | cut -d'=' -f2 | cut -d'[' -f1 | tr -d '[:space:]')

mapfile -t state < <( xinput --list-props $id| grep 'Device Enabled' | cut -d':' -f2 | tr -d '[:space:]')
 
if [ $state = '1' ]; then
	xinput --set-prop $id 'Device Enabled' 0
	zenity --notification --text='Touchpad Disabled'
elif [ $state = '0' ];then
	xinput --set-prop $id 'Device Enabled' 1
	zenity --notification --text='Touchpad Enabled'
fi
